# Test System: Windows 10
# Test Java Version:
# 	java version "1.8.0_121"
# 	Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
# 	Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

compile:
	@javac statistics.java -encoding utf8

test:
	@javac statistics.java -encoding utf8
	@java statistics

clean:
	rm -rf *.class
