# Wrote By Kingsley, 2018.12
# Develop Environment: gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
# For the labs of Operating Systems

C = gcc

lab1-11:
	$(C) -o lab1/an_ch2_lb lab1/an_ch2_lb.c
	./lab1/an_ch2_lb

lab1-12:
	$(C) -o lab1/an_ch2_la lab1/an_ch2_la.c
	./lab1/an_ch2_la

lab1-2:
	$(C) -pthread -o lab1/thread_test lab1/thread_test.c
	./lab1/thread_test



lab4-1:
	$(C) -o lab4/doit lab4/doit.c
	./lab4/doit

lab4-2:
	$(C) -o lab4/myshell lab4/myshell.c
	./lab4/myshell
