# Wrote By Kingsley, 2018.12
# Develop Environment: gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
# For the labs of Operating Systems

C = gcc

lab1-11:
	$(C) -o lab1/an_ch2_lb lab1/an_ch2_lb.c
	./lab1/an_ch2_lb

lab1-12:
	$(C) -o lab1/an_ch2_la lab1/an_ch2_la.c
	./lab1/an_ch2_la

lab1-2:
	$(C) -pthread -o lab1/thread_test lab1/thread_test.c
	./lab1/thread_test



lab2-1:
	$(C) -o lab2/producer_consumer lab2/producer_consumer.c
	./lab2/producer_consumer

lab2-2:
	$(C) -pthread -o lab2/barber lab2/barber.c
	./lab2/barber

lab2-3:
	$(C) -o lab2/reader_writer lab2/reader_writer.c
	./lab2/reader_writer



lab3-0:
	$(C) -o lab3/myfind lab3/myfind.c
	./lab3/myfind



lab4-1:
	$(C) -o lab4/doit lab4/doit.c
	./lab4/doit

lab4-2:
	$(C) -o lab4/myshell lab4/myshell.c
	./lab4/myshell
